# Generated by Django 2.1.10 on 2020-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bag',
            field=models.ManyToManyField(to='discord_game.Item'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='life',
            field=models.IntegerField(default=100),
        ),
    ]
