# Generated by Django 2.1.10 on 2020-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_game', '0002_auto_20200201_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_reference', models.CharField(max_length=50, unique=True)),
                ('area_row_max_size', models.IntegerField(default=1)),
                ('area_column_max_size', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_reference', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='actual_x_position',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='actual_y_position',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
