# Generated by Django 2.1.10 on 2020-02-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_game', '0004_auto_20200201_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_game.Item')),
            ],
        ),
    ]
