# Generated by Django 2.1.10 on 2020-02-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_game', '0005_carryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bag',
            field=models.ManyToManyField(to='discord_game.CarryItem'),
        ),
    ]
