# Generated by Django 2.1.10 on 2020-02-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_game', '0006_auto_20200202_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
