  
version: '3'

services:

  kessel_db:
    image: mariadb:10.3
    env_file: kessel/environment/kessel.env

  kessel:
    build: .    
    image: kessel:devel
    restart: on-failure
    container_name: kessel_container
    command: gunicorn -w 3 kessel.wsgi:application -b :5666
    env_file: kessel/environment/kessel.env
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "5666:5666"
    depends_on:
      - kessel_db

volumes:
  static_data: